### ISSUE TITLE
Request for permission to cite this opensource in a paper

### ISSUE THREAD

**Issue by SangbaekYoo** [medipixel/Deep_reinforcement_learning_for_guidewire_navigation_in_coronary_artery_phantom#1]
Thank you for sharing the excellent open source. 
I want to cite this GitHub link in the paper I am currently working on because I used the pre-trained agent.

Could you please let me know that it is acceptable to cite the related paper 
```
J. Kweon et al., "Deep Reinforcement Learning for Guidewire Navigation in Coronary Artery Phantom," in IEEE Access, vol. 9, pp. 166409-166422, 2021
```
and include this open source link?

**Comment by MrSyee** [comment]
Sure. It's great to hear that this work is helpful for your work.

**Comment by SangbaekYoo** [comment]
@MrSyee Thank you! :)
